workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1

    environment:
      java: 17
      node: 18

    scripts:
      - name: Install npm dependencies
        script: npm install

      - name: Build web app
        script: npm run build

      - name: Sync Capacitor
        script: npx cap sync android

      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk

    publishing:
      email:
        recipients:
          - sahmaboiii@gmail.com
